CREATE TABLE IF NOT EXISTS characters (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    server TEXT,
    level INTEGER,
    profession TEXT,
    silverCoins INTEGER DEFAULT 0,
    demonTribute INTEGER DEFAULT 0,
    favorite BOOLEAN DEFAULT FALSE,
    lastActive TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    combatPower INTEGER DEFAULT 0,
    questProgress JSONB DEFAULT '{}',
    inventory JSONB DEFAULT '{}',
    equipment JSONB DEFAULT '{}',
    skills JSONB DEFAULT '{}',
    completedDailyTasks JSONB DEFAULT '{}',
    completedWeeklyTasks JSONB DEFAULT '{}',
    equippedItems JSONB DEFAULT '{}',
    craftingQueues JSONB DEFAULT '{}',
    favoriteCraftingFacilities JSONB DEFAULT '{}',
    favoriteItems JSONB DEFAULT '{}',
    currencyTimers JSONB DEFAULT '{}',
    gems JSONB DEFAULT '{}',
    starSeals JSONB DEFAULT '{}',
    guildName TEXT,
    guildRank TEXT,
    createdAt TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
